# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2
jobs:
  releasebuild:
    docker:
      - image: debian:unstable

    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -y -qq --no-install-recommends sudo automake autoconf libglib2.0-dev libtool intltool python3-dev python-gi python-gi-dev cython dh-autoreconf libbluetooth-dev gtk-update-icon-cache python-pip
      - run: ./autogen.sh
      - run: make
      - run: make distcheck
      - run: sudo make install

  flake8-3.6:
      docker:
        - image: circleci/python:3.6

      steps:
        - checkout
        - run: python3 -m pip install --user flake8
        - run: python3 -m flake8

  flake8-3.7:
      docker:
        - image: circleci/python:3.7

      steps:
        - checkout
        - run: python3 -m pip install --user flake8
        - run: python3 -m flake8

  flake8-3.8:
      docker:
        - image: circleci/python:3.8.0b1

      steps:
        - checkout
        - run: python3 -m pip install --user flake8
        - run: python3 -m flake8

  mypy-3.6:
      docker:
        - image: circleci/python:3.6

      steps:
        - checkout
        - run: python3 -m pip install --user mypy
        - run: python3 -m mypy -p blueman --ignore-missing-imports --warn-unused-configs --disallow-untyped-calls --disallow-incomplete-defs --disallow-untyped-decorators --no-implicit-optional --warn-redundant-casts --warn-unused-ignores --warn-return-any --disallow-any-generics

  mypy-3.7:
      docker:
        - image: circleci/python:3.7

      steps:
        - checkout
        - run: python3 -m pip install --user mypy
        - run: python3 -m mypy -p blueman --ignore-missing-imports --warn-unused-configs --disallow-untyped-calls --disallow-incomplete-defs --disallow-untyped-decorators --no-implicit-optional --warn-redundant-casts --warn-unused-ignores --warn-return-any --disallow-any-generics

  mypy-3.8:
      docker:
        - image: circleci/python:3.8.0b1

      steps:
        - checkout
        - run: python3 -m pip install --user mypy
        - run: python3 -m mypy -p blueman --ignore-missing-imports --warn-unused-configs --disallow-untyped-calls --disallow-incomplete-defs --disallow-untyped-decorators --no-implicit-optional --warn-redundant-casts --warn-unused-ignores --warn-return-any --disallow-any-generics

workflows:
  version: 2
  build_and_test:
    jobs:
      - releasebuild
      - flake8-3.6
      - flake8-3.7
      - flake8-3.8
      - mypy-3.6
      - mypy-3.7
      - mypy-3.8
